apiVersion: v1
kind: Service
metadata:
  name: sample-elasticsearch-discovery
  namespace: elk-test
spec:
  clusterIP: None
  selector:
    service: sample-elasticsearch
  ports:
  - name: transport
    port: 9300