apiVersion: v1
kind: Service
metadata:
  name: sample-kibana
  namespace: elk
  labels:
    component: sample-kibana
spec:
  type: ClusterIP
  selector:
    component: sample-kibana
  ports:
  - name: http
    port: 80
    targetPort: http