apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-logstash-configmap
  namespace: default
data:
  logstash.yml: |
    xpack.monitoring.elasticsearch.url: http://sample-elasticsearch:9200
    dead_letter_queue.enable: true
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.username: logstash_system 
    xpack.monitoring.elasticsearch.password: Password1$
  pipelines.yml: |
    - pipeline.id: azureeventhubs
      path.config: "/usr/share/logstash/azureeventhubs.cfg"
  azureeventhubs.cfg: |
    input {
      tcp {
        port => 5000
      }
      http {
            port => 31311
            codec => json
        }
    }

    filter {
      json{
        source => "message"
        target => "field"
      }
    }


    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        user => "elastic"
        password => "changeme"
      }
    }
  logstash.conf: |