apiVersion: v1
kind: Service
metadata:
  name: sample-logstash
  namespace: elk
  labels:
    component: sample-logstash
spec:
  type: ClusterIP
  selector:
    component: sample-logstash
  ports:
  - name: http
    port: 31311
    targetPort: http