apiVersion: v1
kind: Service
metadata:
  name: sample-logstash
  namespace: elk-test
  labels:
    component: sample-logstash
spec:
  type: LoadBalancer
  selector:
    component: sample-logstash
  ports:
  - name: tcp
    port: 5000
    nodePort: 31301
    targetPort: tcp
  - name: http
    port: 31311
    nodePort: 31312
    targetPort: http