apiVersion: v1
kind: ConfigMap
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string, not a Python "NoneType"
    actions:
      1:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y-%m-%d'
          unit: days
          unit_count: 4
          field:
          stats_result:
          epoch:
          exclude: False
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string, not a Python "NoneType"
    client:
      hosts:
        - sample-elasticsearch
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key: 
      ssl_no_validate: False
      http_auth: "elastic:Telefonica.2021.elk+"
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: []

metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"action_file.yml":"---\n# Remember, leave a key empty if there is no value.  None will be a string, not a Python \"NoneType\"\nactions:\n  1:\n    action: delete_indices\n    description: \"Clean up ES by deleting old indices\"\n    options:\n      timeout_override:\n      continue_if_exception: False\n      disable_action: False\n      ignore_empty_list: True\n    filters:\n    - filtertype: age\n      source: name\n      direction: older\n      timestring: '%Y.%m.%d'\n      unit: days\n      unit_count: 10\n      field:\n      stats_result:\n      epoch:\n      exclude: False","config.yml":"---\n# Remember, leave a key empty if there is no value.  None will be a string, not a Python \"NoneType\"\nclient:\n  hosts:\n    - elasticsearch\n  port: 9200\n  url_prefix:\n  use_ssl: False\n  certificate:\n  client_cert:\n  client_key:\n  ssl_no_validate: False\n  http_auth:\n  timeout: 30\n  master_only: False\n\nlogging:\n  loglevel: INFO\n  logfile:\n  logformat: default\n  blacklist: []"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"elasticsearch","stack":"management"},"name":"elasticsearch-curator","namespace":"elk"}}
  creationTimestamp: "2019-07-31T18:53:14Z"
  labels:
    app: elasticsearch
    stack: management
  name: elasticsearch-curator
  namespace: elk