# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"labels":{"job":"elasticsearch-curator","stack":"management"},"name":"elasticsearch-curator","namespace":"elk"},"spec":{"jobTemplate":{"metadata":{"labels":{"job":"elasticsearch-curator","stack":"management","type":"job-cron"}},"spec":{"template":{"metadata":{"labels":{"job":"elasticsearch-curator","stack":"management","type":"job-cron"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"agentpool","operator":"In","values":["management"]}]}]}}},"automountServiceAccountToken":false,"containers":[{"args":["--config","/etc/config/config.yml","/etc/config/action_file.yml"],"image":"quay.io/pires/docker-elasticsearch-curator:5.5.4","name":"curator","volumeMounts":[{"mountPath":"/etc/config","name":"config"}]}],"restartPolicy":"OnFailure","volumes":[{"configMap":{"name":"elasticsearch-curator"},"name":"config"}]}}}},"schedule":"1 0 * * *"}}
  creationTimestamp: "2019-07-31T18:53:19Z"
  labels:
    job: elasticsearch-curator
    stack: management
  name: elasticsearch-curator
  namespace: elk
  resourceVersion: "180799741"
  selfLink: /apis/batch/v1beta1/namespaces/elk/cronjobs/elasticsearch-curator
  uid: 767eb985-b3c4-11e9-a4ca-000d3a13ca82
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        job: elasticsearch-curator
        stack: management
        type: job-cron
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            job: elasticsearch-curator
            stack: management
            type: job-cron
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: service
                        operator: In
                        values:
                          - sample-elasticsearch
                  topologyKey: "kubernetes.io/hostname"
          automountServiceAccountToken: false
          containers:
            - args:
                - --config
                - /etc/config/config.yml
                - /etc/config/action_file.yml
              image: bobrik/curator:5.8.1
              imagePullPolicy: IfNotPresent
              name: curator
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/config
                  name: config
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: elasticsearch-curator
              name: config
  schedule: 1 0 * * *
  successfulJobsHistoryLimit: 5
  suspend: false
status:
  lastScheduleTime: "2020-08-02T00:01:00Z"
