apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  creationTimestamp: "2020-07-22T19:53:55Z"
  labels:
    job: elasticsearch-curator
    stack: management
    type: job-cron
  name: elasticsearch-curator
  namespace: elk

spec:
  backoffLimit: 7
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels: 
        job: elasticsearch-curator
        job-name: elasticsearch-curator
        stack: management
        type: job-cron
    spec:
      affinity:
         podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - sample-elasticsearch
            topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      containers:
      - args:
        - --config
        - /etc/config/config.yml
        - /etc/config/action_file.yml
        image: unifiedstreaming/curator:5.5.1
        imagePullPolicy: IfNotPresent
        name: curator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: elasticsearch-curator
        name: config