apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-logstash-extractor
  namespace: elk
  labels:
    component: sample-logstash-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
     component: sample-logstash-extractor
  template:
    metadata:
      labels:
        component: sample-logstash-extractor
    spec:
      containers:
      - name: sample-logstash-extractor
        image: docker.elastic.co/logstash/logstash:7.8.0
        volumeMounts:
        - name: sample-logstash-extractor-configmap
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: sample-logstash-extractor-configmap
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        - name: sample-logstash-extractor-configmap
          mountPath: /usr/share/logstash/logstash.cfg
          subPath: logstash.cfg  
        - name: sample-logstash-extractor-configmap
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 31300
          name: tcp
        - containerPort: 31311
          name: http
      volumes:
        - name: sample-logstash-extractor-configmap
          configMap:
            name: sample-logstash-extractor-configmap