apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilepvcaz
  namespace: elk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 100Gi