apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    job: elasticsearch-extractor
    stack: management
  name: elasticsearch-extractor
  namespace: elk
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        job: elasticsearch-extractor
        stack: management
        type: job-cron
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            job: elasticsearch-curator
            stack: management
            type: job-cron
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: service
                        operator: In
                        values:
                          - sample-elasticsearch
                  topologyKey: "kubernetes.io/hostname"
          automountServiceAccountToken: false
          containers:
          - name: sample-logstash-extractor-configmap
            image: docker.elastic.co/logstash/logstash:7.8.0
            volumeMounts:
            - name: sample-logstash-extractor-configmap
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: sample-logstash-extractor-configmap
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: sample-logstash-extractor-configmap
              mountPath: /usr/share/logstash/logstash.cfg
              subPath: logstash.cfg  
            - name: sample-logstash-extractor-configmap
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml
            - name: azure
              mountPath: /data
            resources:
              limits:
                cpu: 1000m
              requests:
                cpu: 100m
            ports:
            - containerPort: 31300
              name: tcp
            - containerPort: 31311
              name: http
          volumes:
            - name: azure
              persistentVolumeClaim:
                claimName: azurefilepvcaz
            - name: sample-logstash-extractor-configmap
              configMap:
                name: sample-logstash-extractor-configmap
          restartPolicy: OnFailure
  schedule: 1 0 * 4 59
  successfulJobsHistoryLimit: 2
  suspend: false
